// reportGenerator.ts
import PDFDocument from "pdfkit";
import { Readable } from "stream";
import { PAGE, COLORS, FONTS, FONT_SIZES } from "./constants";
import { drawHeader } from "./header";
import { drawFooter } from "./footer";
import {
  formatDate,
  formatCurrency,
  drawSectionTitle,
  drawSeparator,
  calculateResolutionRate,
} from "./helpers";
import { drawCaseBlock } from "./caseBlock";

// ============================================================================
// SUMMARY CARD
// ============================================================================

const drawSummaryCard = (
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  width: number,
  height: number,
  label: string,
  value: string,
  color: string,
): void => {
  doc.roundedRect(x, y, width, height, 8).fillColor(COLORS.accent).fill();
  doc.rect(x, y, 3, height).fillColor(color).fill();
  doc
    .fontSize(7)
    .font(FONTS.regular)
    .fillColor(COLORS.gray)
    .text(label.toUpperCase(), x + 12, y + 12, {
      width: width - 18,
      lineBreak: false,
    });
  doc
    .fontSize(16)
    .font(FONTS.bold)
    .fillColor(COLORS.dark)
    .text(value, x + 12, y + 28, { width: width - 18, lineBreak: false });
};

// ============================================================================
// REPORT METADATA
// ============================================================================

const drawReportMetadata = (doc: PDFKit.PDFDocument, options: any): void => {
  // doc
  //   .fontSize(FONT_SIZES.title)
  //   .font(FONTS.bold)
  //   .fillColor(COLORS.dark)
  //   .text(options.title.toUpperCase(), { align: "center" });
  // doc.moveDown(0.5);
  doc
    .fontSize(FONT_SIZES.small)
    .font(FONTS.regular)
    .fillColor(COLORS.gray)
    .text(
      `Period: ${formatDate(options.startDate)} — ${formatDate(options.endDate)}`,
      { align: "right" },
    )
    .text(`Generated By: ${options.generatedBy || "System"}`, {
      align: "right",
    })
    .text(
      `Report Type: ${options.reportType === "overall" ? "Overall Compliance" : "Cases Report"}`,
      { align: "right" },
    );
  doc.moveDown(1);
  drawSeparator(doc);
};

// ============================================================================
// EXECUTIVE SUMMARY
// ============================================================================

const drawExecutiveSummary = (doc: PDFKit.PDFDocument, options: any): void => {
  drawSectionTitle(doc, "Executive Summary");

  const cardWidth = 150;
  const cardHeight = 58;
  const cardGap = 12;
  const cardsPerRow = 3;
  const totalGridWidth = cardsPerRow * cardWidth + (cardsPerRow - 1) * cardGap;
  const startX = PAGE.MARGIN + (PAGE.CONTENT_WIDTH - totalGridWidth) / 2;

  const summaryCards = [
    {
      label: "Total Cases",
      value: String(options.summary.totalCases || 0),
      color: COLORS.primary,
    },
    {
      label: "Resolved Cases",
      value: String(options.summary.resolvedCases || 0),
      color: COLORS.primaryLight,
    },
    {
      label: "Pending Cases",
      value: String(options.summary.pendingCases || 0),
      color: COLORS.warning,
    },
    {
      label: "Total Penalty",
      value: formatCurrency(options.summary.totalPenalty || 0),
      color: COLORS.primary,
    },
    {
      label: "Total Paid",
      value: formatCurrency(options.summary.totalPaid || 0),
      color: COLORS.primaryLight,
    },
    {
      label: "Outstanding",
      value: formatCurrency(options.summary.outstandingBalance || 0),
      color: COLORS.danger,
    },
  ];

  const cardRows = Math.ceil(summaryCards.length / cardsPerRow);
  const cardStartY = doc.y + 5;

  summaryCards.forEach((card, idx) => {
    const col = idx % cardsPerRow;
    const row = Math.floor(idx / cardsPerRow);
    drawSummaryCard(
      doc,
      startX + col * (cardWidth + cardGap),
      cardStartY + row * (cardHeight + cardGap),
      cardWidth,
      cardHeight,
      card.label,
      card.value,
      card.color,
    );
  });

  doc.y = cardStartY + cardRows * (cardHeight + cardGap) + 15;

  const resolutionRate = calculateResolutionRate(
    options.summary.resolvedCases || 0,
    options.summary.totalCases || 0,
  );

  doc
    .fontSize(FONT_SIZES.small)
    .font(FONTS.regular)
    .fillColor(COLORS.gray)
    .text(
      `Resolution Rate: ${resolutionRate}%  •  Outstanding: ${formatCurrency(options.summary.outstandingBalance || 0)}`,
      { align: "center" },
    );
  doc.moveDown(0.5);
};

// ============================================================================
// MAIN GENERATOR
// ============================================================================

const reportGenerator = (options: any): Readable => {
  const doc = new PDFDocument({
    margin: PAGE.MARGIN,
    bufferPages: true,
    size: "A4",
  });

  const stream = new Readable({ read() {} });
  doc.on("data", (chunk: Buffer) => stream.push(chunk));
  doc.on("end", () => stream.push(null));

  // ============ PAGE 1 ============
  drawHeader(doc, options.title);
  drawReportMetadata(doc, options);
  drawExecutiveSummary(doc, options);

  // ============ CASE DETAILS ============
  if (options.cases && options.cases.length > 0) {
    // Only add a new page for cases - don't add if we just started
    doc.addPage();
    drawHeader(doc, "CASE DETAILS");

    options.cases.forEach((caseData: any, idx: number) => {
      drawCaseBlock(doc, caseData, drawHeader);

      // Only draw separator if not the last case
      if (idx < options.cases.length - 1) {
        drawSeparator(doc);
      }
    });
  } else {
    doc.addPage();
    drawHeader(doc, "CASE DETAILS");

    doc
      .fontSize(11)
      .font(FONTS.regular)
      .fillColor(COLORS.gray)
      .text("No cases found for the specified criteria.", PAGE.MARGIN, doc.y, {
        align: "center",
      });
  }

  // ============ DISCLAIMER ============
  // Only add page if we're near the bottom
  if (doc.y > PAGE.HEIGHT - PAGE.FOOTER_MARGIN - 80) {
    doc.addPage();
    drawHeader(doc, options.title);
  }

  doc.moveDown(1);
  drawSeparator(doc);

  doc
    .fontSize(FONT_SIZES.tiny)
    .font(FONTS.regular)
    .fillColor(COLORS.gray)
    .text(
      "This is an official document generated by the Corporate Affairs Commission Compliance Management System. " +
        "The information contained herein is confidential and intended solely for authorized personnel. " +
        "Unauthorized distribution or reproduction of this document is strictly prohibited.",
      PAGE.MARGIN,
      doc.y,
      { align: "center", width: PAGE.CONTENT_WIDTH },
    );

  // ============ DRAW FOOTERS ON ALL PAGES ============
  // Do this ONCE at the very end, before doc.end()
  try {
    const range = doc.bufferedPageRange();
    const totalPages = range.count;

    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      drawFooter(doc);
    }

    // Switch back to the last page so doc.end() works correctly
    if (totalPages > 0) {
      doc.switchToPage(totalPages - 1);
    }
  } catch (err) {
    console.warn("Footer rendering warning:", (err as Error).message);
  }

  doc.end();
  return stream;
};

export default reportGenerator;
